import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <header className="nav">
          <div className="container nav-inner">
            <div className="brand">Canvas Projects</div>
            <nav className="nav-links">
              <a className="nav-link" href="/projects" suppressHydrationWarning>Projects</a>
              <a className="nav-link" href="/docs" suppressHydrationWarning>Docs</a>
            </nav>
          </div>
        </header>
        <main className="container animate-in">
          {children}
        </main>
      </body>
    </html>
  );
}
